spring:
  application:
    name: brave-msg-mail
  mail:
    host: smtp.qq.com
    username: 3152217587
    password: sfwmthqdvvtvdcjh
    default-encoding: UTF-8
    sender: 3152217587@qq.com
    nick-name: Brave